# Generated by Django 3.1.7 on 2021-04-02 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bujo_app', '0002_auto_20210402_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='../static/css/images/')),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='bujo_app.profiledetails')),
            ],
        ),
    ]
