# Generated by Django 3.1.7 on 2021-04-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bujo_app', '0003_profilepic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePic',
        ),
    ]
