# Generated by Django 3.1.7 on 2021-04-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bujo_app', '0004_delete_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='../static/css/images/'),
        ),
    ]
