# Generated by Django 3.1.7 on 2021-04-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bujo_app', '0006_auto_20210403_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThisWeekItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_item_type', models.CharField(choices=[('task', 'Task'), ('event', 'Event'), ('note', 'Note')], max_length=10)),
                ('item_details', models.CharField(max_length=100)),
            ],
        ),
    ]
