# Generated by Django 3.1.7 on 2021-04-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bujo_app', '0007_thisweekitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_item_type', models.CharField(choices=[('Task', 'task'), ('Event', 'event'), ('Note', 'note')], max_length=10)),
                ('item_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='thisweekitems',
            name='chosen_item_type',
            field=models.CharField(choices=[('Task', 'task'), ('Event', 'event'), ('Note', 'note')], max_length=10),
        ),
    ]
