# Generated by Django 3.1.7 on 2021-04-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bujo_app', '0008_auto_20210404_0202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePic',
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='profile_pic',
            field=models.ImageField(default='static/images/userpic.jpg', upload_to='../static/css/images/'),
        ),
        migrations.AlterField(
            model_name='thisweekitems',
            name='chosen_item_type',
            field=models.CharField(choices=[('Task', 'Task'), ('Event', 'Event'), ('Note', 'Note')], max_length=10),
        ),
        migrations.AlterField(
            model_name='todayitems',
            name='chosen_item_type',
            field=models.CharField(choices=[('Task', 'Task'), ('Event', 'Event'), ('Note', 'Note')], max_length=10),
        ),
    ]
