# Generated by Django 3.1.7 on 2021-04-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bujo_app', '0011_profiledetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledetails',
            name='user',
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='profile_pic',
            field=models.ImageField(default='/static/images/userpic.png', upload_to='images/'),
        ),
    ]
