# Generated by Django 3.1.7 on 2021-04-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bujo_app', '0012_auto_20210404_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='profile_pic',
            field=models.ImageField(default='images/defaultpic.png', upload_to='images/'),
        ),
    ]
